// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rjxyfpyhnpmiqrswkvga.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJqeHlmcHlobnBtaXFyc3drdmdhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3NjI5MDAsImV4cCI6MjA3MzMzODkwMH0.Cuar47N5GZlfi3fED1FJHVgJ3W8WIjoxg8uWwL7et4Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});